version: "2"
services:
  plumber:
    image: crazycapivara/plumber:rstudio_news
    ports:
      - "8005:8000"
  flask:
    image: crazycapivara/flask
    ports:
      - "5010:5000"
  flask_rapi:
    image: crazycapivara/flask
    command: use_template.py
    ports:
      - "5005:5000"
  lb:
    image: dockercloud/haproxy
    environment:
      - HTTP_BASIC_AUTH=fry:fry
    ports:
      - "5080:80"
      - "1936:1936"
    links:
      - flask
      - flask_rapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

