jobs:
  - name: science
    plan:
      - task: silly
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rocker/r-base

          inputs:
            - name: bender

          run:
            path: ./bender/build.sh

