version: "2"
services:
  bender:
    image: rocker/shiny
    ports:
      - "4848:3838"
  express:
    image: crazycapivara/express
    volumes:
      - ./scripts:/app
    command: sh -c "ping -c 2 bender && npm install express passport passport-http && node werkstatt.js"
    #command: ["npm install express passport passport-http",  "node werkstatt.js"]
    ports:
      - "3020:3000"
    #fry:
  #  image: rocker/shiny

