version: "2"
services:
  minicran:
    image: crazycapivara/minicran
    volumes:
      - ./scripts:/scripts
      - ./repo:/miniCRAN
    command: r /scripts/create_repo.R 
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./repo:/usr/share/nginx/html

