concurrent = 1
check_interval = 0

[[runners]]
  name = "bender"
  url = "http://192.168.70.111:9090/"
  token = "3bd3d65fd0fe66bcece672a2eb7603"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "rocker/rstudio"
    privileged = false
    disable_cache = false
    volumes = ["/home/bender/tmp:/gitlab_ci", "/cache"]
    shm_size = 0
    pull_policy = "never"
  [runners.cache]

[[runners]]
  name = "shell"
  url = "http://192.168.70.111:9090/"
  token = "18966edfa44fb133af631ba1b2fbe1"
  executor = "shell"
  [runners.cache]
