version: "2"
services:
# bender:
#    image: rocker/shiny
#    ports:
#      - "3939:3838"
# fry:
#    image: rocker/shiny
#    ports:
#      - "4949:3838"
 bender:
   image: crazycapivara/flask
   ports:
     - "5010:5000"
 fry:
   image: crazycapivara/flask
   ports:
     - "5020:5000" 
 lb:
    image: crazycapivara/haproxy
    environment:
      - ADDITIONAL_BACKEND_bck_fry=server fry fry:5000 check inter 2000 rise 2 fall 3
      #- EXTRA_FRONTEND_SETTINGS_80=acl fry path_beg -i /fry,use_backend bck_fry if fry
      - EXTRA_FRONTEND_SETTINGS_80=acl isFry urlp(bck) fry,use_backend bck_fry if isFry
    #  - HTTP_BASIC_AUTH=fry:fry
    ports:
      - "5080:80"
      - "1936:1936"
    links:
      - bender
    #  - flask_rapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

