version: "2"
services:
# bender:
#    image: rocker/shiny
#    ports:
#      - "3939:3838"
# fry:
#    image: rocker/shiny
#    ports:
#      - "4949:3838"
 rstudio:
   image: rocker/rstudio
   ports:
     - "9797:8787"
 shiny:
   image: rocker/shiny
   ports:
     - "3939:3838" 
 lb:
    image: dockercloud/haproxy
    environment:
      - ADDITIONAL_BACKEND_bck_rstudio=server rstudio rstudio:8787 check inter 2000 rise 2 fall 3
      #- EXTRA_FRONTEND_SETTINGS_80=acl fry path_beg -i /fry,use_backend bck_fry if fry
      - EXTRA_FRONTEND_SETTINGS_80=acl isRStudio urlp(bck) rstudio,use_backend bck_rstudio if isRStudio
      #- HTTP_BASIC_AUTH=fry:fry
    ports:
      - "5080:80"
      - "1936:1936"
    links:
      - shiny
    #  - flask_rapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

